### ISSUE TITLE
Custom Headers

### ISSUE THREAD

**Issue by carmas123** [ClusterWS/ClusterWS-Client-JS#36]
### Submitting

- [ ] Bug
- [X ] Question
- [ ] Suggetion
- [ ] Other

### Details
Please can you explain me how I can add a custom header to pass an authorization token into header?

**Comment by goriunov** [comment]
Unfortunately browser WebSocket does not support  headers, check out this one https://github.com/websockets/ws/issues/467

**Comment by carmas123** [comment]
Ok I found a solution. Save the header data into cookie and it will be passed to the Ws headers.
Regards

**Comment by shwarcu** [comment]
@carmas123  could you please share how to exactly do this?

**Comment by carmas123** [comment]
Sorry man but I solved the problem some years ago and I don't remember how I do that. However now I use other framework and I migrate all to Socket.Io
